### ISSUE TITLE
Github workflow breaking since Ubuntu 20.04

### ISSUE THREAD

**Issue by rbricheno** [pimoroni/icm20948-python#15]
ubuntu-latest was recently changed to 20.04 which makes `.github/workflows/test.yml` fail for python 3.4.

The failing test reports the error:
```
Version 3.4 was not found in the local cache
Error: Version 3.4 with arch x64 not found
```
You can avoid this by either specifying ubuntu-18.04 in your workflow or removing python 3.4 for x64. See here for more information: https://github.com/actions/setup-python/issues/185#issuecomment-768232756

**Comment by Gadgetoid** [comment]
Thank you- I've been slowly fixing these as I come across them since this blew up CI across basically all of our libraries. I've been dropping Python 3.4 support. Frustratingly the link to a list of versions given by GitHub Actions when it throws this error clearly includes 3.4, but perhaps I was overlooking the distro differences. Maybe using `ubuntu-latest` if I want CI not to break spontaneously is a bad idea :laughing: - though that said, it's good to revisit these things every now and then.
